#!/usr/bin/env node
/**
 * IMDb Ratings CSV → src/data/films.ts
 *
 * ── HOW TO EXPORT FROM IMDB ─────────────────────────────────────────────────
 *  1. Go to https://www.imdb.com/user/p.5u7f6lubcjejompimc5ypd6quy/ratings/
 *     (or your ratings page while logged in)
 *  2. Click the three-dot menu ⋮ at the top-right of the ratings list
 *  3. Select "Export" — IMDb downloads a file called "ratings.csv"
 *
 * ── HOW TO RUN ──────────────────────────────────────────────────────────────
 *  node scripts/import-imdb.js path/to/ratings.csv
 *
 * ── WHAT IT DOES ────────────────────────────────────────────────────────────
 *  • Imports all movies (skips TV series, episodes, video games)
 *  • Omits the date you rated each film (as requested)
 *  • Preserves any myTake notes you've manually written
 *  • Overwrites src/data/films.ts with the full list
 *  • Run `npm run build` afterwards to rebuild the site
 */

const fs   = require('fs')
const path = require('path')

const csvPath = process.argv[2]
if (!csvPath) {
  console.error('Usage: node scripts/import-imdb.js <path-to-ratings.csv>')
  process.exit(1)
}
if (!fs.existsSync(csvPath)) {
  console.error(`File not found: ${csvPath}`)
  process.exit(1)
}

// ── CSV parser ───────────────────────────────────────────────────────────────
function parseCSVLine(line) {
  const fields = []
  let cur = '', inQ = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (c === '"') {
      if (inQ && line[i + 1] === '"') { cur += '"'; i++ }
      else inQ = !inQ
    } else if (c === ',' && !inQ) {
      fields.push(cur.trim())
      cur = ''
    } else {
      cur += c
    }
  }
  fields.push(cur.trim())
  return fields
}

// ── Parse CSV ────────────────────────────────────────────────────────────────
const lines = fs.readFileSync(csvPath, 'utf-8')
  .split('\n')
  .map(l => l.trim())
  .filter(Boolean)

const headers = parseCSVLine(lines[0]).map(h => h.trim())
const col = name => headers.indexOf(name)

// IMDb CSV columns we use:
//   Title, Year, Title Type, Genres, Directors, Your Rating
// We intentionally ignore: Position, Const, Created (date rated), Modified,
//   Description, URL, IMDb Rating, Runtime (mins), Num Votes, Release Date

const MOVIE_TYPES = new Set(['movie', 'tvmovie', 'short', 'video'])

const films = lines.slice(1)
  .map(line => {
    const cols = parseCSVLine(line)
    if (cols.length < 5) return null

    const titleType = (cols[col('Title Type')] || '').toLowerCase().replace(/\s/g, '')
    if (!MOVIE_TYPES.has(titleType)) return null

    const myRating = parseInt(cols[col('Your Rating')], 10)
    if (!myRating || myRating < 1) return null

    const title    = cols[col('Title')]?.trim()
    const year     = parseInt(cols[col('Year')], 10)
    const genre    = (cols[col('Genres')] || '').split(',').map(g => g.trim()).filter(Boolean)
    const director = (cols[col('Directors')] || 'Unknown').split(',')[0].trim()

    if (!title || !year) return null
    return { title, year, myRating, genre, director }
  })
  .filter(Boolean)
  .sort((a, b) => b.myRating - a.myRating || b.year - a.year)

// ── Preserve existing myTake annotations ────────────────────────────────────
const takesMap = {}
try {
  const existing = fs.readFileSync(
    path.join(__dirname, '../src/data/films.ts'), 'utf-8'
  )
  // Match  myTake: 'some text'  or  myTake: "some text"
  const re = /title:\s*['"]([^'"]+)['"][\s\S]*?myTake:\s*['"]([^'"]+)['"]/g
  let m
  while ((m = re.exec(existing)) !== null) takesMap[m[1]] = m[2]
} catch (_) {}

const filmsWithTakes = films.map(f =>
  takesMap[f.title] ? { ...f, myTake: takesMap[f.title] } : f
)

// ── Write films.ts ───────────────────────────────────────────────────────────
const outPath  = path.join(__dirname, '../src/data/films.ts')
const filmJSON = JSON.stringify(filmsWithTakes, null, 2)

const output = `// Auto-generated by scripts/import-imdb.js — do not edit manually.
// To regenerate: node scripts/import-imdb.js ratings.csv

export type Film = {
  title: string
  year: number
  myRating: number
  genre: string[]
  director: string
  myTake?: string
}

export const films: Film[] = ${filmJSON}

export default films
`

fs.writeFileSync(outPath, output, 'utf-8')

const preserved = Object.keys(takesMap).filter(t => filmsWithTakes.some(f => f.title === t))
console.log(`✓ Imported   ${films.length} films  →  src/data/films.ts`)
if (preserved.length) {
  console.log(`✓ Preserved  ${preserved.length} personal takes`)
}
console.log(`\nNext step: npm run build`)
